Vagrant.configure("2") do |config|

 	config.vm.define "centos" do |subconfig|    
		subconfig.vm.box = "bento/centos-7.1"
		subconfig.vm.hostname="centos"    
		subconfig.vm.network "private_network", ip: "192.168.56.11"    
		subconfig.vm.provider "virtualbox" do |vb|      
			vb.memory = "256"      
			vb.cpus = "1"    
		end
                subconfig.vm.provision "shell", inline: <<-SHELL
                      yum -y install vim gcc
                      useradd user
                      cp -r /home/vagrant/.ssh /home/user/.ssh
                      chown user:user -R /home/user
                SHELL
	 end

	config.vm.define "ubuntu" do |subconfig|
		subconfig.vm.box ="bencer/dirtycow"
		subconfig.vm.box_version ="0.1"
		subconfig.vm.hostname="ubuntu"
		subconfig.vm.network "private_network", ip: "192.168.56.12"
		subconfig.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
			vb.cpus = "1"
			vb.gui = false
			vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
		end
                subconfig.vm.provision "shell", inline: <<-SHELL
                      apt-get install -y gcc build-essential g++
                      useradd user
                      mkdir /home/user
                      cp -r /home/vagrant/.ssh /home/user/.ssh
                      cp /etc/skel/.bashrc /home/user/
                      chown user:user -R /home/user
                SHELL
	end

end


